spring:
  application:
    name: queue-service

  profiles:
    include: kafka

  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configserver:"

  cloud:
    # ECS Fargate에서 Eureka에 자기 IP를 ECS 메타데이터 IP(169.254.172.2)가 아닌 VPC 내부 IP(172.31.x.x)로 등록되게 하기 위한 설정.
    inetutils:
      preferred-networks:
        - 10\.
        - 172\.
        - 192\.168\.

    config:
      username: ${CONFIG_SERVER_USERNAME:}
      password: ${CONFIG_SERVER_PASSWORD:}
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
